### ISSUE TITLE
Building script on x64

### ISSUE THREAD

**Issue by LionBlazer** [Georgeto/gothic3sdk#2]
Hello
I have successfully built your scripts on the x32 architecture, namely Script_LearnPoints. But when I try to build the project on the x64 architecture, I get a lot of compilation errors, all the same type:
![изображение](https://user-images.githubusercontent.com/41360863/60762010-2afb6800-a05e-11e9-8f2f-f26bf7ffc8d1.png)
![изображение](https://user-images.githubusercontent.com/41360863/60762032-02c03900-a05f-11e9-9be9-6afc6ceaf4d1.png)
How can I fix this?
Sorry for my bad c++ knowledge

**Comment by georgeto** [comment]
Building for x64 is not supported, because there is no point in doing so, as Gothic 3 is a 32-bit application.
