### ISSUE TITLE
Editing update pack

### ISSUE THREAD

**Issue by sisiri** [Georgeto/gothic3sdk#6]
greeting mates, dear developers, im not as advanced in c++ as it obviously required for working in this field, but i hope ill find the way to achieve some positive changes in my beloved game, and beg you help

as you may heart, update pack developer realised beta version 1.05 of his patch and fell asleep (i dont know any details, hope he's going well), and its changes are generally marvelous, but unfortunately one of them ruins all the experience of gothic 3. whenever creatures make their strong attack, they have some kind of immunity, so now, fighting one boar is challenging and fighting group of them is a death sentence in all ways(ye again, again). 

update pack 1.05 doesn't have its own installer, so we just have to install v1.04 first, then throw some canged dll files into game folder to install v1.05, and my idea was to compare files of gothic 3 with update pack 1.04 with following files of v1.05, replace them randomly until the desired feature is removed. to do this i want to do reverse disassembly of each files, so i can compare them and change source code. 

all this prelude was necessary and i can now ask if its possible to turn following .dll files of v1.04&v1.05 into pure code and compare them? thanks in advance

**Comment by georgeto** [comment]
> all this prelude was necessary and i can now ask if its possible to turn following .dll files of v1.04&v1.05 into pure code and compare them? thanks in advance

No, it is generally not possible to convert the .dll's back into the source code they were compiled from. But there are tools with whom it is possible to analyze and also compare .dll files, one prominent and free example being [Ghidra](https://ghidra-sre.org/). It even contains a feature named "Program Differences" which you can use to diff the .dlls of Update Pack v1.04 and v1.05.

**Comment by sisiri** [comment]
i see, well, it seems i have to ask update pack author for his own pure code of changed files, it has to be much harder, but anyway, thanks a lot meow
