### ISSUE TITLE
How to create headers linked with G3

### ISSUE THREAD

**Issue by LionBlazer** [Georgeto/gothic3sdk#7]
Hello
I ran into a problem: I needed to call functions from gCMap_PS, but their definitions aren't provided in the sdk

![image](https://github.com/georgeto/gothic3sdk/assets/41360863/10352bef-8074-4496-9238-64f6cd74fce9)

I tried to restore the definition from the decompiled code Game.dll

![image](https://github.com/georgeto/gothic3sdk/assets/41360863/eb5b6ca9-a77f-4d19-9ebc-62acefaa56d1)
![image](https://github.com/georgeto/gothic3sdk/assets/41360863/fc0820a0-b69a-41b5-bcb2-69cf40497575)

But apparently I'm doing something wrong, because during the CalcUV call, the game crashes.
Can you tell me how to add definitions from the game?

**Comment by georgeto** [comment]
> But apparently I'm doing something wrong, because during the CalcUV call, the game crashes.
Can you tell me how to add definitions from the game?

The problem is that you have declared the function as virtual, although in fact it is not a virtual function.
If you remove the `virtual` specifier, calling the `CalcUV` function should work as expected.

Well, not quite yet, because now you will get a linker error complaining that it can't find the `CalcUV` function.
The reason is that your declaration of `CalcUV`is missing the `const` specifier.

With these changes, the function declaration is exactly what can be seen in your Ghidra decompiler screenshot, i.e. is what is exported by `Game.dll`.

I have attached the header for `gCMap_PS` in case you want to access additional methods.
[ge_map_ps.zip](https://github.com/georgeto/gothic3sdk/files/11548135/ge_map_ps.zip)

**Comment by LionBlazer** [comment]
Thanks, game has stopped crashing.
But apparently the problem was not only this:
Maybe I am incorrectly passing a pointer to gCMap_PS to my function, is it legal to do this?

_mCCallHook Hook1;
void GE_STDCALL fun1(CFFGFCWnd* param_1) {
    hook_base(param_1, (gCMap_PS *)(param_1 + 0x10)); // is it correct?
}_

_(*(gCMap_PS **)(param_1 + 0x10) crashes)_

I inject the hook with following code:

_Hook1.Prepare(RVA_Game(0xa87d9), &fun1)
         .AddRegArg(mCRegisterBase::mERegisterType_Edi)
         .InsertCall().Hook();_

address in game.dll:
![image](https://github.com/georgeto/gothic3sdk/assets/41360863/f28a11e2-e971-4b1c-bbfa-38cc8f937653)

I took the offset 0x10 based on this fragment
![image](https://github.com/georgeto/gothic3sdk/assets/41360863/dc78ea41-44da-45dd-94a8-f1ae2a2dd964)

------
My current code doesn't crash game but any access to gCMap_PS returns zeros, an attempt to write something produces crash.

`void hook_base(CFFGFCWnd* param_1, gCMap_PS* map) {

    bCVector playerPos = Entity::GetPlayer().GetInstance()->GetWorldPosition();

    GEFloat u = 0.0;
    GEFloat v = 0.0;
    map->CalcUV(playerPos, u, v);


    // text rendering
    CFFGFCDeviceContext* context = param_1->GetDC();
    std::string s = std::to_string((unsigned long long) map);
    bCString str = VectorToString(bCVector(u, v, 0)) /* always undefined value */ + " " + VectorToString(playerPos);
    bCRect rect(100, 100, 200, 200);

    context->CalcTextRect(0, str.GetUnicodeText(), -1, rect, 0x25);
    bCFloatAlphaColor b_c_float_alpha_color(1);
    bCFloatAlphaColor b_c_float_alpha_color2(0x100a8bb6);
    param_1->GetClientRect(rect);
    context->DrawTextA(0, str.GetUnicodeText(), -1, &rect, 0x25, b_c_float_alpha_color, &b_c_float_alpha_color2);


    //icon drawing
    CFFGFCBitmap icon;
    icon.Create("TEST.png");

    bCRect rect2(u, v, u + 30, v + 30);
    context->DrawBitmap(&icon, &rect2, 0, 0.0);
}`

when trying to output UV, an "undefined" value is output:
<img width="723" alt="image" src="https://github.com/georgeto/gothic3sdk/assets/41360863/7a3ce498-66f7-48a2-8207-af4832ecbdc2">

**Comment by georgeto** [comment]
> mCCallHook Hook1;
> void GE_STDCALL fun1(CFFGFCWnd* param_1) {
> hook_base(param_1, (gCMap_PS *)(param_1 + 0x10)); // is it correct?
> }

The pointer arithmetic here is subtly wrong.
`param_1` is of type `CFFGFCWnd *`, i.e. a pointer to a `CFFGFCWnd` object.
Therefore the address resulting from `param_1 + 0x10` is actually `param_1 + 0x10 * sizeof(CFFGFCWnd)`.
To get the result you expect, you first have to cast param_1 to a byte sized pointer (e.g. `GELPByte`, which is defined as `unsigned char *`):
`(gCMap_PS *)((GELPByte)param_1 + 0x10)`

Ghidra probably does not know the size of the CFFGFCWnd type, and thus simply assumes a size of one (byte), so the decompiler output is misleading.

(For a more descriptive explanation how pointer arithmetic works see for example [here](https://www.learncpp.com/cpp-tutorial/pointer-arithmetic-and-array-indexing/)).


-------

> My current code doesn't crash game but any access to gCMap_PS returns zeros, an attempt to write something produces crash.

If no map is currently selected, the pointer to gCMap_PS is null. If you then invoke CalcUV this will cause a crash.
To detect this situation, you can simply check for map being != null.

Or as an alternative, move your hook further down into the function, for example `RVA_Game(0xA8811)`, and rely on the check that is already present in FUN_100a87f0 (whose actual name is by the way gCHUDStaticMap::OnPaint), see the if condition in line 32.
Don't forget to then also adjust `.AddRegArg(mCRegisterBase::mERegisterType_Edi)` to use `mERegisterType_Esi` instead.

**Comment by LionBlazer** [comment]
Thank you, I added cast to byte, and everything worked. 
`hook_base(param_1, *(gCMap_PS **)((GELPByte)param_1 + 0x10));`
